compressionLevel: 0

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - win32
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.2.1.cjs
